### PR TITLE
fix(workspace): stop devkit tests racing their own build, add hookTimeout floor

### PR DESCRIPTION
**Pull request by ofri-peretz**
## Summary

Three related pre-push flakes that block **unrelated** pushes. All are invisible to CI — which builds once, serially, on a cold runner — and all were hit while shipping #351.

**1. Root cause: devkit's test raced its own build.** turbo's `test` declares `dependsOn: ["^build"]`, which orders only *upstream* builds. So `@interlace/eslint-devkit#build` — scheduled because every plugin depends on devkit — ran **concurrently with** `@interlace/eslint-devkit#test`. [`scripts/build-package.ts:47`](scripts/build-package.ts) `rmSync`s `dist` before rebuilding, and [`no-runtime-optional-peer.test.ts:31`](packages/eslint-devkit/src/no-runtime-optional-peer.test.ts) scans that same `dist/src` — so it failed with `ENOENT: scandir .../eslint-devkit/dist/src` under load and passed when run alone. Fixed with a Package Configuration pinning devkit's test to its own `build`.

  > Scoped to devkit **deliberately**: setting `dependsOn: ["build"]` at the root pulls docs' full Next build into every `turbo run test` and pushed the pre-commit `tests-affected` hook past **four minutes**. devkit is the only package whose suite actually reads its own `dist` (the `express-security` match is rule *fixture code*, not a filesystem read).

**2. Pre-push ran two turbo processes at once.** `parallel: true` started `build` and `tests` concurrently; separate turbo invocations don't share a task graph, so both executed the same `#build` tasks and collided with `ENOTEMPTY, Directory not empty: .../dist`. `shim-verify` sat in a third parallel slot reading `dist` mid-rewrite, producing `shim threw on require — Cannot find module .../dist/src/index.js` for a *different package each run*. All three are now one sequential command; everything else in the hook still runs in parallel.

**3. `hookTimeout` floor.** PR #324 set `testTimeout: 30_000` across all 21 vitest configs, but `hookTimeout` stayed at Vitest's 10s default in **every one**. `testTimeout` does not cover `beforeAll`/`beforeEach`/`afterEach`, so a hook starved by the parallel fan-out still fails as `Hook timed out in 10000ms` — exactly how devkit's fixture failed in #351. A safety net, **not** a substitute for cheap fixtures: #351 fixed that fixture by deleting its I/O.

## Test plan

- [x] **Every lock verified to fail on its unfixed state** (`scripts/__tests__/prepush-and-vitest-timeouts.lock.test.ts`, 7 assertions):
  - remove `packages/eslint-devkit/turbo.json` → `packages/eslint-devkit (no turbo.json)` ❌
  - `turbo.json`/configs from `origin/main` → all three other assertions ❌
- [x] **Neither scan can pass vacuously** — one asserts it finds ≥20 vitest configs, the other asserts it finds the known dist-reading suite.
- [x] `turbo run test --dry=json` confirms the intended graph: `devkit#test → devkit#build`, while `docs#test` still pulls **only** upstream builds (no docs build), and devkit's `inputs`/`outputs` are preserved for caching.
- [x] `turbo run test --filter="...[origin/main]"`: **61/61 successful**.
- [x] **Pushed with no `LEFTHOOK_EXCLUDE` at all** — every pre-push hook green, including the new `build-tests-shim-verify`. Shipping #351 required `LEFTHOOK_EXCLUDE=build` to get past this same race.

## After merge

Pre-push stops failing nondeterministically on `dist`, so agents and humans stop needing `LEFTHOOK_EXCLUDE=build` to push unrelated work. Tooling-only — an empty changeset is included, so no package is released.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

File: scripts/__tests__/prepush-and-vitest-timeouts.lock.test.ts [hunk 1]
```diff
@@ -0,0 +1,220 @@
...
+        const full = path.join(dir, entry.name);
+        if (entry.isDirectory()) walk(full);
+        else if (/\.test\.tsx?$/.test(entry.name)) {
+          const src = fs.readFileSync(full, 'utf-8');
+          // e.g. resolve(__dirname, '..', 'dist', 'src')
+          const buildsDistPath = /(resolve|join)\([^)]*['"]dist['"]/.test(src);
+          // Rule tests embed strings like `express.static(path.join(__dirname,
+          // 'dist'))` as *fixture code* — they never touch the filesystem. A
+          // suite that genuinely reads its own dist has to import node:fs.
+          const readsFilesystem = /from\s+['"](node:)?fs['"]/.test(src);
```
[the remark this answers is not in the document]
Comment (ofri-peretz) [reply scripts/__tests__/prepush-and-vitest-timeouts.lock.test.ts]: Fixed in ce34c8b7 — good catch, and this is the failure mode that matters most in a lock: it would have kept passing while silently covering less.

```diff
-const readsFilesystem = /from\s+['"](node:)?fs['"]/.test(src);
+const readsFilesystem = /from\s+['"](node:)?fs(\/promises)?['"]/.test(src);
```

Verified the widening is exact rather than a catch-all:

| import | matches |
|---|---|
| `from 'fs'` | yes |
| `from 'node:fs'` | yes |
| `from 'fs/promises'` | **yes (was no)** |
| `from 'node:fs/promises'` | **yes (was no)** |
| `from 'node:fsx'` | no |

The `finds the known dist-reading suite` anti-vacuousness assertion still passes, so the guard is still proven to match something real — 8 tests green.
