### PR TITLE
fix(eslint-formatter): ship the schema its exports declare

### PR DESCRIPTION
**Pull request by ofri-peretz**
The 0.2.0 release never reached npm, and **not for the reason I predicted**.

I expected the npm-token wall from [#916](https://github.com/ofri-peretz/eslint/issues/916). It failed earlier than that — Dist integrity failed, cancelling its siblings and skipping the publish job entirely, so neither package shipped. `eslint-plugin-import-next` is still at 2.7.5.

The gate was right:

```
❌ 1 declared export path(s) missing from the tarball:
   @interlace/eslint-formatter  "./schema.json" -> schema.json  (NOT SHIPPED)
   A consumer importing that subpath gets "Cannot find module".

❌ 1 package(s) missing discoverability metadata:
   @interlace/eslint-formatter  funding
```

Both defects are mine, and both are only observable once the package is actually **packed** — the same reason `private: true` hid its missing build script and its broken emit layout in #928.

## The cause

`build-package.ts` publishes FROM `dist/` and copied a fixed asset list — `README.md`, `LICENSE`, `.npmignore`. A root asset a package declares in `files` never made the tarball. `schema.json` is in this package's `files` **and** mapped by `exports`, and still did not ship.

It now also copies any root-level file the manifest says it ships, skipping directories since `src/` and `dist/` are the build's own output. **That fixes the class rather than the instance** — the next package to declare a root asset gets it shipped without touching this script.

`funding` added, matching `eslint-formatter-sarif` and `eslint-devkit`.

## Test plan

- [x] Verified by **packing**, not reading: `tar tzf` now lists `package/schema.json`.
- [x] Published-artifact gate passes across **all 33 packages** — every declared export resolves, metadata complete, 3,613.8 kB unpacked.
- [x] Full build of all 33 packages clean.
- [x] Patch changeset included.

## After merge

The release retries. It will then reach the step I originally expected and stop there: the npm token cannot create a new package under the `@interlace` scope, which now blocks **two** packages (#916). One token fix ships both.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by ofri-peretz** [comment]
Superseded by #935, which landed the same two fixes while this was in review — and did the build change **better than mine**.

We hit the same failure and reached the same diagnosis independently. The difference is one I got wrong:

My version copied every root-level file named in `files`. `@interlace/eslint-formatter` lists `CHANGELOG.md` in `files`, so mine would have started shipping changelogs again — 225 kB across the ecosystem that `build-package.ts` deliberately excludes, with the rationale documented a few lines above the code I was editing. I reintroduced the thing the surrounding comment exists to prevent.

#935 has `EXCLUDED_ASSETS = new Set(['CHANGELOG.md'])` and keeps that exclusion explicit. Its framing is also sharper: the hardcoded list was a *third* hand-maintained inventory beside `files` and `exports`, and the three had drifted.

Verified main end to end by packing, not reading:

```
$ tar tzf interlace-eslint-formatter-*.tgz | grep -E 'schema|CHANGELOG'
package/schema.json
```

`schema.json` ships, `CHANGELOG.md` does not, and `funding` is present on main. Both defects from the failed 0.2.0 release are fixed there, so there is nothing left in this branch worth carrying.

The release can retry. It will now get past Dist integrity and stop at the step I originally expected — the npm token cannot create a new package under the `@interlace` scope (#916), which blocks both formatters.
